

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_doctor_performance';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_daily_queue_status';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE smart_scheduler_pkg';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  FOR t IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'NOTIFICATIONS', 'DELAY_LOG', 'QUEUE_STATUS', 'DOCTOR_AVAILABILITY',
      'CONSULTATIONS', 'APPOINTMENTS', 'DOCTORS', 'PATIENTS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  phone VARCHAR2(20) NOT NULL UNIQUE,
  email VARCHAR2(120) UNIQUE,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT chk_patient_name CHECK (LENGTH(TRIM(name)) >= 2),
  CONSTRAINT chk_patient_email CHECK (email IS NULL OR INSTR(email, '@') > 1)
);

CREATE TABLE doctors (
  doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  specialization VARCHAR2(100) NOT NULL,
  avg_consult_time NUMBER DEFAULT 3 NOT NULL,
  is_active CHAR(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT chk_avg_consult_time CHECK (avg_consult_time BETWEEN 1 AND 90),
  CONSTRAINT chk_doctor_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  scheduled_time DATE NOT NULL,
  appointment_type VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
  status VARCHAR2(30) DEFAULT 'BOOKED' NOT NULL,
  priority NUMBER DEFAULT 1 NOT NULL,
  check_in_time DATE,
  notes VARCHAR2(500),
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_app_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
  CONSTRAINT fk_app_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE CASCADE,
  CONSTRAINT chk_app_type CHECK (appointment_type IN ('SCHEDULED', 'WALK_IN', 'EMERGENCY')),
  CONSTRAINT chk_app_status CHECK (status IN ('BOOKED', 'CHECKED_IN', 'IN_CONSULTATION', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
  CONSTRAINT chk_app_priority CHECK (priority BETWEEN 0 AND 3)
);

CREATE UNIQUE INDEX ux_doctor_slot_active
ON appointments (
  CASE WHEN appointment_type = 'SCHEDULED'
        AND status IN ('BOOKED', 'CHECKED_IN', 'IN_CONSULTATION')
       THEN doctor_id END,
  CASE WHEN appointment_type = 'SCHEDULED'
        AND status IN ('BOOKED', 'CHECKED_IN', 'IN_CONSULTATION')
       THEN scheduled_time END
);

CREATE INDEX idx_app_doctor_time ON appointments(doctor_id, scheduled_time);
CREATE INDEX idx_app_patient ON appointments(patient_id);
CREATE INDEX idx_app_checkin ON appointments(check_in_time);

CREATE TABLE consultations (
  consultation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id NUMBER NOT NULL UNIQUE,
  start_time DATE NOT NULL,
  end_time DATE,
  duration NUMBER,
  CONSTRAINT fk_consult_app FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE,
  CONSTRAINT chk_consult_duration CHECK (duration IS NULL OR duration >= 1)
);

CREATE TABLE doctor_availability (
  availability_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id NUMBER NOT NULL,
  break_start_time DATE NOT NULL,
  break_duration NUMBER NOT NULL,
  status VARCHAR2(20) DEFAULT 'UNAVAILABLE' NOT NULL,
  reason VARCHAR2(250),
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_avail_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE CASCADE,
  CONSTRAINT chk_break_duration CHECK (break_duration > 0),
  CONSTRAINT chk_avail_status CHECK (status IN ('AVAILABLE', 'UNAVAILABLE'))
);

CREATE TABLE queue_status (
  queue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id NUMBER NOT NULL UNIQUE,
  queue_position NUMBER NOT NULL,
  estimated_time DATE NOT NULL,
  last_updated DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_queue_app FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE,
  CONSTRAINT chk_queue_position CHECK (queue_position > 0)
);

CREATE TABLE delay_log (
  delay_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id NUMBER NOT NULL,
  appointment_id NUMBER,
  delay_minutes NUMBER NOT NULL,
  message VARCHAR2(500) NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_delay_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE CASCADE,
  CONSTRAINT fk_delay_app FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE SET NULL
);

CREATE TABLE notifications (
  notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id NUMBER NOT NULL,
  message VARCHAR2(500) NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  read_at DATE,
  CONSTRAINT fk_note_app FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE
);

CREATE OR REPLACE VIEW v_daily_queue_status AS
SELECT
  a.appointment_id,
  p.name AS patient_name,
  d.name AS doctor_name,
  d.specialization,
  a.scheduled_time,
  a.appointment_type,
  a.status,
  q.queue_position,
  q.estimated_time
FROM appointments a
JOIN patients p ON p.patient_id = a.patient_id
JOIN doctors d ON d.doctor_id = a.doctor_id
LEFT JOIN queue_status q ON q.appointment_id = a.appointment_id;

CREATE OR REPLACE VIEW v_doctor_performance AS
SELECT
  d.doctor_id,
  d.name,
  d.specialization,
  COUNT(a.appointment_id) AS total_appointments,
  SUM(CASE WHEN a.status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed_appointments,
  ROUND(AVG(c.duration), 1) AS actual_avg_duration
FROM doctors d
LEFT JOIN appointments a ON a.doctor_id = d.doctor_id
LEFT JOIN consultations c ON c.appointment_id = a.appointment_id
GROUP BY d.doctor_id, d.name, d.specialization;

CREATE OR REPLACE PACKAGE smart_scheduler_pkg AS
  grace_minutes CONSTANT NUMBER := 10;
  slot_step_minutes CONSTANT NUMBER := 15;

  FUNCTION calc_avg_duration(p_doctor_id NUMBER) RETURN NUMBER;
  FUNCTION check_grace(p_appointment_id NUMBER, p_arrival_time DATE) RETURN VARCHAR2;
  FUNCTION get_wait_time(p_appointment_id NUMBER) RETURN NUMBER;
  FUNCTION next_slot(
    p_doctor_id NUMBER,
    p_from_time DATE,
    p_ignore_appointment_id NUMBER DEFAULT NULL
  ) RETURN DATE;

  PROCEDURE recalc_queue(p_doctor_id NUMBER, p_day DATE);
  PROCEDURE book_appointment(
    p_patient_id NUMBER,
    p_doctor_id NUMBER,
    p_scheduled_time DATE,
    p_appointment_type VARCHAR2 DEFAULT 'SCHEDULED',
    p_notes VARCHAR2 DEFAULT NULL,
    p_appointment_id OUT NUMBER
  );
  PROCEDURE process_checkin(p_appointment_id NUMBER, p_arrival_time DATE DEFAULT SYSDATE);
  PROCEDURE start_consultation(p_appointment_id NUMBER);
  PROCEDURE finish_consultation(p_appointment_id NUMBER);
  PROCEDURE cancel_appointment(p_appointment_id NUMBER);
  PROCEDURE reschedule_appointment(p_appointment_id NUMBER, p_new_time DATE);
  PROCEDURE handle_doctor_unavailability(
    p_doctor_id NUMBER,
    p_break_start DATE,
    p_break_duration NUMBER,
    p_reason VARCHAR2 DEFAULT 'Doctor unavailable'
  );
  PROCEDURE notify_patients(p_doctor_id NUMBER, p_day DATE, p_message VARCHAR2);
END smart_scheduler_pkg;
/

CREATE OR REPLACE PACKAGE BODY smart_scheduler_pkg AS
  FUNCTION calc_avg_duration(p_doctor_id NUMBER) RETURN NUMBER IS
    v_avg NUMBER;
  BEGIN
    SELECT ROUND(AVG(duration))
    INTO v_avg
    FROM (
      SELECT c.duration
      FROM consultations c
      JOIN appointments a ON a.appointment_id = c.appointment_id
      WHERE a.doctor_id = p_doctor_id
        AND c.duration IS NOT NULL
      ORDER BY c.consultation_id DESC
    )
    WHERE ROWNUM <= 10;

    RETURN NVL(v_avg, 3);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN 3;
  END calc_avg_duration;

  FUNCTION check_grace(p_appointment_id NUMBER, p_arrival_time DATE) RETURN VARCHAR2 IS
    v_scheduled DATE;
  BEGIN
    SELECT scheduled_time
    INTO v_scheduled
    FROM appointments
    WHERE appointment_id = p_appointment_id;

    IF p_arrival_time <= v_scheduled + (grace_minutes / 1440) THEN
      RETURN 'WITHIN_GRACE';
    END IF;

    RETURN 'LATE';
  END check_grace;

  FUNCTION get_wait_time(p_appointment_id NUMBER) RETURN NUMBER IS
    v_eta DATE;
  BEGIN
    SELECT estimated_time
    INTO v_eta
    FROM queue_status
    WHERE appointment_id = p_appointment_id;

    RETURN GREATEST(0, ROUND((v_eta - SYSDATE) * 24 * 60));
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN NULL;
  END get_wait_time;

  FUNCTION next_slot(
    p_doctor_id NUMBER,
    p_from_time DATE,
    p_ignore_appointment_id NUMBER
  ) RETURN DATE IS
    v_slot DATE := p_from_time;
    v_count NUMBER;
  BEGIN
    LOOP
      SELECT COUNT(*)
      INTO v_count
      FROM appointments
      WHERE doctor_id = p_doctor_id
        AND scheduled_time = v_slot
        AND appointment_type = 'SCHEDULED'
        AND status IN ('BOOKED', 'CHECKED_IN', 'IN_CONSULTATION')
        AND (p_ignore_appointment_id IS NULL OR appointment_id <> p_ignore_appointment_id);

      IF v_count = 0 THEN
        RETURN v_slot;
      END IF;

      v_slot := v_slot + (slot_step_minutes / 1440);
    END LOOP;
  END next_slot;

  PROCEDURE recalc_queue(p_doctor_id NUMBER, p_day DATE) IS
    CURSOR c_queue IS
      SELECT appointment_id, scheduled_time, appointment_type, status
      FROM appointments
      WHERE doctor_id = p_doctor_id
        AND TRUNC(scheduled_time) = TRUNC(p_day)
        AND status IN ('BOOKED', 'CHECKED_IN', 'IN_CONSULTATION')
      ORDER BY
        CASE appointment_type WHEN 'EMERGENCY' THEN 0 WHEN 'SCHEDULED' THEN 1 ELSE 2 END,
        CASE WHEN appointment_type = 'SCHEDULED' THEN scheduled_time ELSE NVL(check_in_time, scheduled_time) END,
        appointment_id;

    v_pos NUMBER := 0;
    v_cursor_time DATE := GREATEST(SYSDATE, TRUNC(p_day));
    v_avg NUMBER := calc_avg_duration(p_doctor_id);
    v_break_end DATE;
    v_start DATE;
  BEGIN
    DELETE FROM queue_status
    WHERE appointment_id IN (
      SELECT appointment_id
      FROM appointments
      WHERE doctor_id = p_doctor_id
        AND TRUNC(scheduled_time) = TRUNC(p_day)
    );

    FOR r IN c_queue LOOP
      v_pos := v_pos + 1;

      IF r.appointment_type = 'SCHEDULED' THEN
        v_cursor_time := GREATEST(v_cursor_time, r.scheduled_time);
      END IF;

      IF r.status = 'IN_CONSULTATION' THEN
        BEGIN
          SELECT start_time
          INTO v_start
          FROM consultations
          WHERE appointment_id = r.appointment_id
            AND end_time IS NULL;
          v_cursor_time := v_start;
        EXCEPTION WHEN NO_DATA_FOUND THEN
          NULL;
        END;
      END IF;

      FOR br IN (
        SELECT break_start_time, break_duration
        FROM doctor_availability
        WHERE doctor_id = p_doctor_id
          AND status = 'UNAVAILABLE'
      ) LOOP
        v_break_end := br.break_start_time + (br.break_duration / 1440);
        IF v_cursor_time BETWEEN br.break_start_time AND v_break_end THEN
          v_cursor_time := v_break_end;
        END IF;
      END LOOP;

      INSERT INTO queue_status(appointment_id, queue_position, estimated_time)
      VALUES (r.appointment_id, v_pos, v_cursor_time);

      v_cursor_time := v_cursor_time + (v_avg / 1440);
    END LOOP;
  END recalc_queue;

  PROCEDURE book_appointment(
    p_patient_id NUMBER,
    p_doctor_id NUMBER,
    p_scheduled_time DATE,
    p_appointment_type VARCHAR2 DEFAULT 'SCHEDULED',
    p_notes VARCHAR2 DEFAULT NULL,
    p_appointment_id OUT NUMBER
  ) IS
    v_type VARCHAR2(20) := UPPER(p_appointment_type);
    v_status VARCHAR2(30) := 'BOOKED';
    v_priority NUMBER := 1;
    v_checkin DATE := NULL;
    v_scheduled_time DATE := p_scheduled_time;
  BEGIN
    IF v_type = 'EMERGENCY' THEN
      v_status := 'CHECKED_IN';
      v_priority := 0;
      v_checkin := SYSDATE;
    ELSIF v_type = 'WALK_IN' THEN
      v_status := 'CHECKED_IN';
      v_priority := 2;
      v_checkin := SYSDATE;
    END IF;

    IF v_type = 'SCHEDULED' THEN
      v_scheduled_time := next_slot(p_doctor_id, p_scheduled_time, NULL);
    END IF;

    INSERT INTO appointments(
      patient_id, doctor_id, scheduled_time, appointment_type,
      status, priority, check_in_time, notes
    )
    VALUES (
      p_patient_id, p_doctor_id, v_scheduled_time, v_type,
      v_status, v_priority, v_checkin, p_notes
    )
    RETURNING appointment_id INTO p_appointment_id;

    recalc_queue(p_doctor_id, v_scheduled_time);
    COMMIT;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20001, 'Schedule conflict: slot was taken by a concurrent booking. Please retry.');
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
  END book_appointment;

  PROCEDURE process_checkin(p_appointment_id NUMBER, p_arrival_time DATE DEFAULT SYSDATE) IS
    v_doctor_id NUMBER;
    v_day DATE;
    v_grace VARCHAR2(20);
  BEGIN
    SELECT doctor_id, scheduled_time
    INTO v_doctor_id, v_day
    FROM appointments
    WHERE appointment_id = p_appointment_id
    FOR UPDATE;

    v_grace := check_grace(p_appointment_id, p_arrival_time);

    IF v_grace = 'WITHIN_GRACE' THEN
      UPDATE appointments
      SET status = 'CHECKED_IN',
          check_in_time = p_arrival_time
      WHERE appointment_id = p_appointment_id;
    ELSE
      UPDATE appointments
      SET status = 'CHECKED_IN',
          appointment_type = 'WALK_IN',
          priority = 2,
          check_in_time = p_arrival_time
      WHERE appointment_id = p_appointment_id;

      INSERT INTO notifications(appointment_id, message)
      VALUES (p_appointment_id, 'Late arrival converted to walk-in after grace period.');
    END IF;

    recalc_queue(v_doctor_id, v_day);
    COMMIT;
  END process_checkin;

  PROCEDURE start_consultation(p_appointment_id NUMBER) IS
    v_doctor_id NUMBER;
    v_day DATE;
    v_active NUMBER;
  BEGIN
    SELECT doctor_id, scheduled_time
    INTO v_doctor_id, v_day
    FROM appointments
    WHERE appointment_id = p_appointment_id
    FOR UPDATE;

    SELECT COUNT(*)
    INTO v_active
    FROM appointments a
    JOIN consultations c ON c.appointment_id = a.appointment_id
    WHERE a.doctor_id = v_doctor_id
      AND a.status = 'IN_CONSULTATION'
      AND c.end_time IS NULL;

    IF v_active > 0 THEN
      RAISE_APPLICATION_ERROR(-20002, 'Doctor already has an active consultation.');
    END IF;

    UPDATE appointments
    SET status = 'IN_CONSULTATION',
        check_in_time = NVL(check_in_time, SYSDATE)
    WHERE appointment_id = p_appointment_id;

    INSERT INTO consultations(appointment_id, start_time)
    VALUES (p_appointment_id, SYSDATE);

    recalc_queue(v_doctor_id, v_day);
    COMMIT;
  END start_consultation;

  PROCEDURE finish_consultation(p_appointment_id NUMBER) IS
    v_doctor_id NUMBER;
    v_day DATE;
  BEGIN
    SELECT doctor_id, scheduled_time
    INTO v_doctor_id, v_day
    FROM appointments
    WHERE appointment_id = p_appointment_id
    FOR UPDATE;

    UPDATE consultations
    SET end_time = SYSDATE
    WHERE appointment_id = p_appointment_id
      AND end_time IS NULL;

    UPDATE appointments
    SET status = 'COMPLETED'
    WHERE appointment_id = p_appointment_id;

    UPDATE doctors
    SET avg_consult_time = calc_avg_duration(v_doctor_id)
    WHERE doctor_id = v_doctor_id;

    recalc_queue(v_doctor_id, v_day);
    COMMIT;
  END finish_consultation;

  PROCEDURE cancel_appointment(p_appointment_id NUMBER) IS
    v_doctor_id NUMBER;
    v_day DATE;
  BEGIN
    SELECT doctor_id, scheduled_time
    INTO v_doctor_id, v_day
    FROM appointments
    WHERE appointment_id = p_appointment_id
    FOR UPDATE;

    UPDATE appointments
    SET status = 'CANCELLED'
    WHERE appointment_id = p_appointment_id;

    DELETE FROM queue_status WHERE appointment_id = p_appointment_id;
    recalc_queue (v_doctor_id, v_day);
    COMMIT;
  END cancel_appointment;

  PROCEDURE reschedule_appointment(p_appointment_id NUMBER, p_new_time DATE) IS
    v_doctor_id NUMBER;
    v_old_time DATE;
    v_new_time DATE;
  BEGIN
    SELECT doctor_id, scheduled_time
    INTO v_doctor_id, v_old_time
    FROM appointments
    WHERE appointment_id = p_appointment_id
    FOR UPDATE;

    v_new_time := next_slot(v_doctor_id, p_new_time, p_appointment_id);

    UPDATE appointments
    SET scheduled_time = v_new_time,
        status = 'BOOKED',
        appointment_type = 'SCHEDULED',
        priority = 1,
        check_in_time = NULL
    WHERE appointment_id = p_appointment_id
      AND status NOT IN ('COMPLETED', 'IN_CONSULTATION');

    recalc_queue(v_doctor_id, v_old_time);
    recalc_queue(v_doctor_id, v_new_time);
    COMMIT;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20003, 'Cannot reschedule: slot was taken by a concurrent booking. Please retry.');
  END reschedule_appointment;

  PROCEDURE handle_doctor_unavailability(
    p_doctor_id NUMBER,
    p_break_start DATE,
    p_break_duration NUMBER,
    p_reason VARCHAR2 DEFAULT 'Doctor unavailable'
  ) IS
  BEGIN
    INSERT INTO doctor_availability(doctor_id, break_start_time, break_duration, status, reason)
    VALUES (p_doctor_id, p_break_start, p_break_duration, 'UNAVAILABLE', p_reason);

    INSERT INTO delay_log(doctor_id, delay_minutes, message)
    VALUES (p_doctor_id, p_break_duration, p_reason);

    notify_patients(p_doctor_id, p_break_start, 'Doctor unavailable. Your estimated consultation time has been recalculated.');
    recalc_queue(p_doctor_id, p_break_start);
    COMMIT;
  END handle_doctor_unavailability;

  PROCEDURE notify_patients(p_doctor_id NUMBER, p_day DATE, p_message VARCHAR2) IS
    CURSOR c_affected IS
      SELECT appointment_id
      FROM appointments
      WHERE doctor_id = p_doctor_id
        AND TRUNC(scheduled_time) = TRUNC(p_day)
        AND status IN ('BOOKED', 'CHECKED_IN');
  BEGIN
    FOR r IN c_affected LOOP
      INSERT INTO notifications(appointment_id, message)
      VALUES (r.appointment_id, p_message);
    END LOOP;
  END notify_patients;
END smart_scheduler_pkg;
/

CREATE OR REPLACE TRIGGER trg_before_appointment_validate
BEFORE INSERT OR UPDATE ON appointments
FOR EACH ROW
BEGIN
  IF :NEW.appointment_type = 'EMERGENCY' THEN
    :NEW.priority := 0;
  ELSIF :NEW.appointment_type = 'SCHEDULED' THEN
    :NEW.priority := 1;
  ELSIF :NEW.appointment_type = 'WALK_IN' THEN
    :NEW.priority := 2;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_before_status_validate
BEFORE UPDATE OF status ON appointments
FOR EACH ROW
BEGIN
  IF :OLD.status = 'COMPLETED' AND :NEW.status <> 'COMPLETED' THEN
    RAISE_APPLICATION_ERROR(-20010, 'Completed appointments cannot move back to another status.');
  END IF;

  IF :OLD.status = 'CANCELLED' AND :NEW.status NOT IN ('CANCELLED', 'BOOKED') THEN
    RAISE_APPLICATION_ERROR(-20011, 'Cancelled appointments can only remain cancelled or be rescheduled.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_after_consultation_duration
BEFORE INSERT OR UPDATE OF end_time ON consultations
FOR EACH ROW
WHEN (NEW.end_time IS NOT NULL)
BEGIN
  :NEW.duration := GREATEST(1, ROUND((:NEW.end_time - :NEW.start_time) * 24 * 60));
END;
/

CREATE OR REPLACE TRIGGER trg_after_consultation_notify
AFTER UPDATE OF end_time ON consultations
FOR EACH ROW
WHEN (NEW.end_time IS NOT NULL)
BEGIN
  INSERT INTO notifications(appointment_id, message)
  VALUES (:NEW.appointment_id, 'Consultation completed. Thank you for visiting.');
END;
/

CREATE OR REPLACE TRIGGER trg_after_cancel_release
AFTER UPDATE OF status ON appointments
FOR EACH ROW
WHEN (NEW.status = 'CANCELLED')
BEGIN
  DELETE FROM queue_status WHERE appointment_id = :NEW.appointment_id;

  INSERT INTO notifications(appointment_id, message)
  VALUES (:NEW.appointment_id, 'Appointment cancelled and slot released for reuse.');
END;
/

CREATE OR REPLACE TRIGGER trg_after_delay_notify
AFTER INSERT ON delay_log
FOR EACH ROW
BEGIN
  INSERT INTO notifications(appointment_id, message)
  SELECT appointment_id, :NEW.message
  FROM appointments
  WHERE doctor_id = :NEW.doctor_id
    AND status IN ('BOOKED', 'CHECKED_IN')
    AND appointment_id = NVL(:NEW.appointment_id, appointment_id);
END;
/

INSERT INTO doctors(name, specialization, avg_consult_time) VALUES ('Dr. Asha Mehta', 'Cardiology', 3);
INSERT INTO doctors(name, specialization, avg_consult_time) VALUES ('Dr. Kabir Anand', 'Orthopedics', 4);
INSERT INTO doctors(name, specialization, avg_consult_time) VALUES ('Dr. Naina Rao', 'Dermatology', 3);

INSERT INTO patients(name, phone, email) VALUES ('Riya Sharma', '9876543210', 'riya@example.com');
INSERT INTO patients(name, phone, email) VALUES ('Arjun Malhotra', '9876543211', 'arjun@example.com');
INSERT INTO patients(name, phone, email) VALUES ('Meera Kapoor', '9876543212', 'meera@example.com');
COMMIT;

DECLARE
  v_id NUMBER;
BEGIN
  smart_scheduler_pkg.book_appointment(1, 1, SYSDATE + (10 / 1440), 'SCHEDULED', 'Seed booking', v_id);
  smart_scheduler_pkg.book_appointment(2, 1, SYSDATE + (15 / 1440), 'SCHEDULED', 'Seed booking', v_id);
  smart_scheduler_pkg.book_appointment(3, 3, SYSDATE + (5 / 1440), 'WALK_IN', 'Walk-in seed', v_id);
END;
/

SELECT * FROM v_daily_queue_status ORDER BY doctor_name, queue_position;
SELECT * FROM v_doctor_performance ORDER BY doctor_id;
